// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/chat/Avatar.vue')['default']
    BaseAppBar: typeof import('./src/components/base/BaseAppBar.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseDialog: typeof import('./src/components/base/BaseDialog.vue')['default']
    BaseDrawer: typeof import('./src/components/base/BaseDrawer.vue')['default']
    BaseDropdown: typeof import('./src/components/base/BaseDropdown.vue')['default']
    BaseFormInput: typeof import('./src/components/base/BaseFormInput.vue')['default']
    BaseImage: typeof import('./src/components/base/BaseImage.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseListItem: typeof import('./src/components/base/BaseListItem.vue')['default']
    BasePopover: typeof import('./src/components/base/BasePopover.vue')['default']
    BaseSpinner: typeof import('./src/components/base/BaseSpinner.vue')['default']
    BaseTooltip: typeof import('./src/components/base/BaseTooltip.vue')['default']
    ConfirmDialog: typeof import('./src/components/shared/ConfirmDialog.vue')['default']
    GgSpinner: typeof import('~icons/gg/spinner')['default']
    HTempest: typeof import('~icons/h/tempest')['default']
    HTempestRaw: typeof import('~icons/h/tempest-raw')['default']
    ImageInput: typeof import('./src/components/chat/ImageInput.vue')['default']
    'Mdi:alert': typeof import('~icons/mdi/alert')['default']
    'Mdi:alertCircleOutline': typeof import('~icons/mdi/alert-circle-outline')['default']
    'Mdi:crosshairsGps': typeof import('~icons/mdi/crosshairs-gps')['default']
    'Mdi:delete': typeof import('~icons/mdi/delete')['default']
    'Mdi:download': typeof import('~icons/mdi/download')['default']
    'Mdi:file': typeof import('~icons/mdi/file')['default']
    'Mdi:loading': typeof import('~icons/mdi/loading')['default']
    'Mdi:picture': typeof import('~icons/mdi/picture')['default']
    MdiAccountMultiple: typeof import('~icons/mdi/account-multiple')['default']
    MdiAdd: typeof import('~icons/mdi/add')['default']
    MdiAlert: typeof import('~icons/mdi/alert')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiCog: typeof import('~icons/mdi/cog')['default']
    MdiDelete: typeof import('~icons/mdi/delete')['default']
    MdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    MdiPound: typeof import('~icons/mdi/pound')['default']
    MdiSend: typeof import('~icons/mdi/send')['default']
    MdiVolume: typeof import('~icons/mdi/volume')['default']
    OutlinedInput: typeof import('./src/components/shared/Inputs/OutlinedInput.vue')['default']
    PlainInput: typeof import('./src/components/shared/Inputs/PlainInput.vue')['default']
    PopInTransition: typeof import('./src/components/transitions/PopInTransition.vue')['default']
    ReloadPrompt: typeof import('./src/components/misc/ReloadPrompt.vue')['default']
    'Twemoji:woozyFace': typeof import('~icons/twemoji/woozy-face')['default']
  }
}

export { }
