// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/chat/Avatar.vue')['default']
    GgSpinner: typeof import('~icons/gg/spinner')['default']
    HAppBar: typeof import('./src/components/shared/HAppBar.vue')['default']
    HBtn: typeof import('./src/components/shared/HBtn.vue')['default']
    HDialog: typeof import('./src/components/shared/HDialog.vue')['default']
    HDIalog: typeof import('./src/components/shared/HDIalog.vue')['default']
    HDrawer: typeof import('./src/components/shared/HDrawer.vue')['default']
    HForm: typeof import('./src/components/shared/HForm.vue')['default']
    HImg: typeof import('./src/components/shared/HImg.vue')['default']
    HInput: typeof import('./src/components/shared/HInput.vue')['default']
    HListItem: typeof import('./src/components/shared/HListItem.vue')['default']
    HPopover: typeof import('./src/components/shared/HPopover.vue')['default']
    HRadio: typeof import('./src/components/shared/HRadio.vue')['default']
    HSpinner: typeof import('./src/components/shared/HSpinner.vue')['default']
    HTempest: typeof import('~icons/h/tempest')['default']
    HTooltip: typeof import('./src/components/shared/HTooltip.vue')['default']
    MdiAccountMultiple: typeof import('~icons/mdi/account-multiple')['default']
    MdiAdd: typeof import('~icons/mdi/add')['default']
    MdiAlert: typeof import('~icons/mdi/alert')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiCog: typeof import('~icons/mdi/cog')['default']
    MdiDelete: typeof import('~icons/mdi/delete')['default']
    MdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    MdiHashtag: typeof import('~icons/mdi/hashtag')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    MdiPound: typeof import('~icons/mdi/pound')['default']
    MdiPoundBox: typeof import('~icons/mdi/pound-box')['default']
    MdiTag: typeof import('~icons/mdi/tag')['default']
    MdiVolume: typeof import('~icons/mdi/volume')['default']
    PopInTransition: typeof import('./src/components/transitions/PopInTransition.vue')['default']
    ReloadPrompt: typeof import('./src/components/misc/ReloadPrompt.vue')['default']
  }
}

export { }
