// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GgSpinner: typeof import('~icons/gg/spinner')['default']
    HBtn: typeof import('./src/components/shared/HBtn.vue')['default']
    HDIalog: typeof import('./src/components/shared/HDIalog.vue')['default']
    HInput: typeof import('./src/components/shared/HInput.vue')['default']
    HListItem: typeof import('./src/components/shared/HListItem.vue')['default']
    HRadio: typeof import('./src/components/shared/HRadio.vue')['default']
    HSpinner: typeof import('./src/components/shared/HSpinner.vue')['default']
    MdiAlert: typeof import('~icons/mdi/alert')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiDelete: typeof import('~icons/mdi/delete')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    PopInTransition: typeof import('./src/components/transitions/PopInTransition.vue')['default']
    ReloadPrompt: typeof import('./src/components/misc/ReloadPrompt.vue')['default']
  }
}

export { }
